email: maxward4@gmail.com
app_username: mward
stack_name: ColumnSemanticSearch
resources_name_prefix: column-search-uid
certificate_arn: arn:aws:acm:us-east-1:938220026554:certificate/b3e1a1e9-a1fc-45f1-8360-02ea65d93fd6
parquet_s3_path: data/parquet
processed_csv_s3_path: data/csv/processed
embeddings_s3_path: embeddings
glue_max_concurrent_runs: 30
sm_processing_instance_count: 1
sm_processing_instance_type: ml.g4dn.xlarge
opensearch_instance_type: r6g.large.search
opensearch_volume_size: 30
models:
- all-MiniLM-L6-v2
- all-distilroberta-v1
- average_word_embeddings_glove.6B.300d
max_batches: 10
local_cpu_architecture: X86_64
